In [39]:
import os
# print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.
import itertools
import os

%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.preprocessing import LabelBinarizer, LabelEncoder
from sklearn.metrics import confusion_matrix

from tensorflow import keras
layers = keras.layers
models = keras.models

In [40]:
dataframe = pd.read_csv("iris.csv")
dataset = dataframe.values
dataset

array([[5.1, 3.5, 1.4, 0.2, 'Setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Setosa'],
       [5.1, 3.3, 1.7, 0.5, 'Setosa'],
       [4.8, 3.4, 1.9, 0.2, 'Setosa'],
       [5.0, 3.0, 1.6, 0.

In [41]:
shuff = dataframe.sample(frac = 1)

In [42]:
print(shuff)

     sepal.length  sepal.width  petal.length  petal.width     variety
25            5.0          3.0           1.6          0.2      Setosa
114           5.8          2.8           5.1          2.4   Virginica
90            5.5          2.6           4.4          1.2  Versicolor
58            6.6          2.9           4.6          1.3  Versicolor
18            5.7          3.8           1.7          0.3      Setosa
..            ...          ...           ...          ...         ...
71            6.1          2.8           4.0          1.3  Versicolor
75            6.6          3.0           4.4          1.4  Versicolor
39            5.1          3.4           1.5          0.2      Setosa
11            4.8          3.4           1.6          0.2      Setosa
23            5.1          3.3           1.7          0.5      Setosa

[150 rows x 5 columns]


In [43]:
train_size = int(len(shuff) * .6)
print ("Train size: %d" % train_size)
print ("Test size: %d" % (len(shuff) - train_size))

Train size: 90
Test size: 60


In [44]:
def train_test_split(data, train_size):
    train = data[:train_size]
    test = data[train_size:]
    return train, test

In [45]:
train_data, test_data = train_test_split(shuff[['sepal.length','sepal.width','petal.length','sepal.length']], train_size)
train_text, test_text = train_test_split(shuff['variety'], train_size)

In [46]:
train_data

sepal.length  sepal.width  petal.length  sepal.length
25            5.0          3.0           1.6           5.0
114           5.8          2.8           5.1           5.8
90            5.5          2.6           4.4           5.5
58            6.6          2.9           4.6           6.6
18            5.7          3.8           1.7           5.7
..            ...          ...           ...           ...
49            5.0          3.3           1.4           5.0
36            5.5          3.5           1.3           5.5
106           4.9          2.5           4.5           4.9
22            4.6          3.6           1.0           4.6
54            6.5          2.8           4.6           6.5

[90 rows x 4 columns]

In [47]:
test_data

sepal.length  sepal.width  petal.length  sepal.length
94            5.6          2.7           4.2           5.6
137           6.4          3.1           5.5           6.4
142           5.8          2.7           5.1           5.8
46            5.1          3.8           1.6           5.1
14            5.8          4.0           1.2           5.8
136           6.3          3.4           5.6           6.3
97            6.2          2.9           4.3           6.2
48            5.3          3.7           1.5           5.3
64            5.6          2.9           3.6           5.6
140           6.7          3.1           5.6           6.7
98            5.1          2.5           3.0           5.1
100           6.3          3.3           6.0           6.3
130           7.4          2.8           6.1           7.4
74            6.4          2.9           4.3           6.4
112           6.8          3.0           5.5           6.8
135           7.7          3.0           6.1           7.7
104           6.5          3.0           5.8           6.5
83            6.0          2.7           5.1           6.0
7             5.0          3.4           1.5           5.0
146           6.3          2.5           5.0           6.3
27            5.2          3.5           1.5           5.2
149           5.9          3.0           5.1           5.9
41            4.5          2.3           1.3           4.5
50            7.0          3.2           4.7           7.0
19            5.1          3.8           1.5           5.1
76            6.8          2.8           4.8           6.8
129           7.2          3.0           5.8           7.2
122           7.7          2.8           6.7           7.7
43            5.0          3.5           1.6           5.0
12            4.8          3.0           1.4           4.8
96            5.7          2.9           4.2           5.7
95            5.7          3.0           4.2           5.7
32            5.2          4.1           1.5           5.2
61            5.9          3.0           4.2           5.9
4             5.0          3.6           1.4           5.0
93            5.0          2.3           3.3           5.0
131           7.9          3.8           6.4           7.9
117           7.7          3.8           6.7           7.7
33            5.5          4.2           1.4           5.5
68            6.2          2.2           4.5           6.2
144           6.7          3.3           5.7           6.7
102           7.1          3.0           5.9           7.1
141           6.9          3.1           5.1           6.9
15            5.7          4.4           1.5           5.7
59            5.2          2.7           3.9           5.2
66            5.6          3.0           4.5           5.6
70            5.9          3.2           4.8           5.9
45            4.8          3.0           1.4           4.8
108           6.7          2.5           5.8           6.7
143           6.8          3.2           5.9           6.8
55            5.7          2.8           4.5           5.7
26            5.0          3.4           1.6           5.0
72            6.3          2.5           4.9           6.3
139           6.9          3.1           5.4           6.9
89            5.5          2.5           4.0           5.5
71            6.1          2.8           4.0           6.1
75            6.6          3.0           4.4           6.6
39            5.1          3.4           1.5           5.1
11            4.8          3.4           1.6           4.8
23            5.1          3.3           1.7           5.1

In [48]:
encoder = LabelEncoder()
encoder.fit(train_text)
y_train = encoder.transform(train_text)
y_test = encoder.transform(test_text)

In [49]:
# Converts the labels to a one-hot representation
num_classes = np.max(y_train) + 1
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [50]:
print('y_train shape:', y_train.shape)
print('y_test shape:', y_test.shape)

y_train shape: (90, 3)
y_test shape: (60, 3)


In [51]:
y_train[0]

array([1., 0., 0.], dtype=float32)

In [53]:
#y_train
test_text.shape
#test_data.shape

(60,)

In [76]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import optimizers
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [108]:
from tensorflow.keras import models
from tensorflow.keras import layers
model = models.Sequential()
model.add(layers.Dense(4, activation='relu', input_shape=(4,)))
#model.add(layers.Dropout(0.5))
model.add(layers.Dense(6, activation='relu'))
#model.add(layers.Dropout(0.5))
model.add(layers.Dense(3, activation='sigmoid'));
model.compile(optimizer='adam',
               loss='categorical_crossentropy',
               metrics=['accuracy'])

In [109]:
history = model.fit(train_data, y_train,batch_size=2,epochs=10,verbose=2,validation_split=0.1)

Train on 81 samples, validate on 9 samples
Epoch 1/10
81/81 - 0s - loss: 1.0324 - accuracy: 0.3210 - val_loss: 1.0042 - val_accuracy: 0.3333
Epoch 2/10
81/81 - 0s - loss: 1.0047 - accuracy: 0.3210 - val_loss: 0.9753 - val_accuracy: 0.3333
Epoch 3/10
81/81 - 0s - loss: 0.9710 - accuracy: 0.3210 - val_loss: 0.9310 - val_accuracy: 0.3333
Epoch 4/10
81/81 - 0s - loss: 0.9078 - accuracy: 0.3210 - val_loss: 0.8436 - val_accuracy: 0.5556
Epoch 5/10
81/81 - 0s - loss: 0.8335 - accuracy: 0.6420 - val_loss: 0.7671 - val_accuracy: 0.5556
Epoch 6/10
81/81 - 0s - loss: 0.7730 - accuracy: 0.5556 - val_loss: 0.7084 - val_accuracy: 0.7778
Epoch 7/10
81/81 - 0s - loss: 0.7207 - accuracy: 0.7901 - val_loss: 0.6458 - val_accuracy: 0.7778
Epoch 8/10
81/81 - 0s - loss: 0.6781 - accuracy: 0.8519 - val_loss: 0.6248 - val_accuracy: 0.8889
Epoch 9/10
81/81 - 0s - loss: 0.6530 - accuracy: 0.7901 - val_loss: 0.5721 - val_accuracy: 1.0000
Epoch 10/10
81/81 - 0s - loss: 0.6118 - accuracy: 0.9136 - val_loss: 0.5349

In [110]:
score = model.evaluate(test_data,y_test,batch_size=2, verbose=1)


60/60 [==============================] - 0s 350us/sample - loss: 0.5839 - accuracy: 0.8000


In [111]:
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.5839044272899627
Test accuracy: 0.8


In [122]:
prediction = model.predict(np.array([test_data.iloc[3]]))

In [123]:
prediction

array([[0.4955384 , 0.29581565, 0.02700397]], dtype=float32)

In [124]:
text_labels = encoder.classes_

In [125]:
predicted_label = text_labels[np.argmax(prediction)]
predicted_label

'Setosa'

In [126]:
print('Actual label:' + test_text.iloc[3])
print("Predicted label: " + predicted_label + "\n") 

Actual label:Setosa
Predicted label: Setosa



In [120]:
test_data.iloc[0]

sepal.length    5.6
sepal.width     2.7
petal.length    4.2
sepal.length    5.6
Name: 94, dtype: float64

In [121]:
test_data

sepal.length  sepal.width  petal.length  sepal.length
94            5.6          2.7           4.2           5.6
137           6.4          3.1           5.5           6.4
142           5.8          2.7           5.1           5.8
46            5.1          3.8           1.6           5.1
14            5.8          4.0           1.2           5.8
136           6.3          3.4           5.6           6.3
97            6.2          2.9           4.3           6.2
48            5.3          3.7           1.5           5.3
64            5.6          2.9           3.6           5.6
140           6.7          3.1           5.6           6.7
98            5.1          2.5           3.0           5.1
100           6.3          3.3           6.0           6.3
130           7.4          2.8           6.1           7.4
74            6.4          2.9           4.3           6.4
112           6.8          3.0           5.5           6.8
135           7.7          3.0           6.1           7.7
104           6.5          3.0           5.8           6.5
83            6.0          2.7           5.1           6.0
7             5.0          3.4           1.5           5.0
146           6.3          2.5           5.0           6.3
27            5.2          3.5           1.5           5.2
149           5.9          3.0           5.1           5.9
41            4.5          2.3           1.3           4.5
50            7.0          3.2           4.7           7.0
19            5.1          3.8           1.5           5.1
76            6.8          2.8           4.8           6.8
129           7.2          3.0           5.8           7.2
122           7.7          2.8           6.7           7.7
43            5.0          3.5           1.6           5.0
12            4.8          3.0           1.4           4.8
96            5.7          2.9           4.2           5.7
95            5.7          3.0           4.2           5.7
32            5.2          4.1           1.5           5.2
61            5.9          3.0           4.2           5.9
4             5.0          3.6           1.4           5.0
93            5.0          2.3           3.3           5.0
131           7.9          3.8           6.4           7.9
117           7.7          3.8           6.7           7.7
33            5.5          4.2           1.4           5.5
68            6.2          2.2           4.5           6.2
144           6.7          3.3           5.7           6.7
102           7.1          3.0           5.9           7.1
141           6.9          3.1           5.1           6.9
15            5.7          4.4           1.5           5.7
59            5.2          2.7           3.9           5.2
66            5.6          3.0           4.5           5.6
70            5.9          3.2           4.8           5.9
45            4.8          3.0           1.4           4.8
108           6.7          2.5           5.8           6.7
143           6.8          3.2           5.9           6.8
55            5.7          2.8           4.5           5.7
26            5.0          3.4           1.6           5.0
72            6.3          2.5           4.9           6.3
139           6.9          3.1           5.4           6.9
89            5.5          2.5           4.0           5.5
71            6.1          2.8           4.0           6.1
75            6.6          3.0           4.4           6.6
39            5.1          3.4           1.5           5.1
11            4.8          3.4           1.6           4.8
23            5.1          3.3           1.7           5.1